// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package repository

import (
	"context"
)

const selectAllJobs = `-- name: SelectAllJobs :many
SELECT id, title, description, created_at, updated_at FROM jobs
`

func (q *Queries) SelectAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, selectAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
